name: Heira Daily Brief (Build & Publish)

on:
  schedule:
    - cron: "0 12 * * *"  # runs every day at 7 AM Central Time
  workflow_dispatch: {}   # allows manual runs from the Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate newsletter
        working-directory: heira_newsletter_kit
        run: python heira_newsletter.py

      - name: Prepare site folder
        run: |
          mkdir -p _site
          cp -r heira_newsletter_kit/output/* _site/
          if [ ! -f "_site/index.html" ]; then
            cp _site/newsletter_web.html _site/index.html || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
