name: Heira Daily Digest

on:
  schedule:
    - cron: "0 13 * * *"   # 8:00 AM Central (13:00 UTC)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests
      - name: Post daily digest
        env:
          SLACK_WEBHOOK_DAILY: ${{ secrets.SLACK_WEBHOOK_DAILY }}
          SLACK_WEBHOOK_URL:   ${{ secrets.SLACK_WEBHOOK_URL }}   # fallback if DAILY not set
        run: python digest_feed.py
